/**
 * Formats content for .cursorrules files.
 * Wraps in a rules-file format with a header comment.
 */
export function formatCursor(assembled: string): string {
  const header = `<!--
  ShipFlow-generated context file
  This file was generated by ShipFlow to provide project context for Cursor.
  Do not edit manually if you want changes to persist across regenerations.
-->

`
  return header + assembled
}
