import { Phase } from "./types";

export const PHASES: Phase[] = [
  {
    id: "01-define", num: 1, name: "Define", icon: "📋", color: "#3B82F6",
    duration: "1-2 days", goal: "Idea → stories → testable acceptance criteria",
    files: [
      { id: "pitch", name: "pitch.md", label: "One-Sentence Pitch", dp: "sara",
        what: "[Product] helps [who] to [do what] by [how].", done: "Stranger gets it in 10 seconds.",
        prompt: `You are a product manager. Help me create a one-sentence pitch.\n\nFormat: [Product] helps [who] to [do what] by [how].\n\nMy rough idea: [DESCRIBE YOUR IDEA HERE]\n\nAlso provide:\n1. Expanded version (2-3 sentences)\n2. What this product is NOT (common misconceptions)\n3. One-line value prop for app store / landing page\n\nFormat as markdown.`,
        template: `# Product Pitch\n\n## One-Sentence\n[Product] helps [who] to [do what] by [how].\n\n## Expanded\n\n## What it is NOT\n- \n\n## App Store Tagline\n` },
      { id: "personas", name: "personas.md", label: "User Personas (1-3)", dp: "sara",
        what: "Who uses this, their pain, current bad solution.", done: "Can name a real person with this problem.",
        prompt: `You are a product manager. Define 1-3 user personas.\n\nProduct: [PASTE PITCH]\n\nFor each persona:\n- Name, age, role/context\n- Specific pain (quantified if possible)\n- Current bad solution and what they hate about it\n- What success looks like for them\n- Tech comfort level (affects UI decisions later)\n- How they'd discover your product\n\nFormat as markdown.`,
        template: `# User Personas\n\n## Persona 1: [Name]\n- **Who**: \n- **Pain**: \n- **Current solution**: \n- **Success**: \n- **Tech level**: \n- **Discovery**: ` },
      { id: "stories", name: "user-stories.md", label: "User Stories (5-10)", dp: "sara",
        what: "'As a [user], I want to [action] so that [benefit].' v1 essentials only.", done: "5-10 stories. Zero nice-to-haves.",
        prompt: `You are a product manager. Write 5-10 user stories for v1.\n\nProduct: [PASTE PITCH]\nUsers: [PASTE PERSONAS]\n\nFormat: "As a [user], I want to [action] so that [benefit]"\n\nRules:\n- Only what's needed for the product to be useful\n- Group: Core (must ship) vs Important (next milestone)\n- List what you deliberately CUT and why\n- Each story must be achievable in 1-2 days of dev work\n- If a story is bigger, break it into smaller stories\n\nFormat as markdown.`,
        template: `# User Stories — v1\n\n## Core (must have)\n1. As a [user], I want to [action] so that [benefit]\n\n## Important (should have — M2)\n\n## Cut from v1 (and why)\n- ` },
      { id: "criteria", name: "acceptance-criteria.md", label: "Acceptance Criteria", dp: "sara",
        what: "Given/When/Then per story. These become tests in Build phase.", done: "Every story has 2-5 testable criteria.",
        prompt: `You are a QA-minded PM. Write acceptance criteria for each story.\n\nStories: [PASTE STORIES]\n\nPer story write 2-5 criteria using:\n- Given [precondition]\n- When [action]\n- Then [expected result]\n\nRules:\n- Include happy path + at least 1 edge case per story\n- Make them specific enough to become automated tests\n- Include error scenarios: what happens when things fail?\n- Include boundary cases: empty input, max length, unauthorized\n\nFormat as markdown with ## per story and ### per criterion.`,
        template: `# Acceptance Criteria\n\n## Story 1: [title]\n### AC 1.1 — Happy path\n- **Given** \n- **When** \n- **Then** \n\n### AC 1.2 — Edge case\n- **Given** \n- **When** \n- **Then** ` },
    ],
    gate: "Every criterion is testable. Vague → rewrite before proceeding.",
  },
  {
    id: "02-design", num: 2, name: "Design System", icon: "🏗️", color: "#8B5CF6",
    duration: "3-5 days", goal: "Architecture, services, data, infra — all decided before code",
    files: [
      { id: "adr", name: "ADR-001-tech-stack.md", label: "ADR-001: Tech Stack", dp: "jordan",
        what: "Every layer chosen with reasoning + tradeoffs.", done: "Can explain every choice.",
        prompt: `You are a CTO. Document the tech stack decision.\n\nProduct: [PASTE PITCH]\nStories: [PASTE STORIES]\nConstraints: Web + iOS + Android. Microservice backend.\n\nStack (already decided — document WHY):\n- Frontend: React Native + Expo SDK 52 (web + iOS + Android)\n- Backend: NestJS microservices (TypeScript)\n- Database: PostgreSQL (per service)\n- ORM: Prisma\n- Auth: [JWT + Passport / Clerk / Supabase Auth — pick one]\n- API Gateway: NestJS gateway or Kong\n- Container: Docker + Kubernetes\n- Cloud: AWS (EKS, RDS, ECR, S3, CloudFront)\n- CI/CD: GitHub Actions → ECR → K8s\n- Monitoring: Sentry (frontend) + Prometheus + Grafana (backend)\n- State: Zustand (frontend)\n- Styling: NativeWind (Tailwind for RN)\n\nFor each layer: choice, alternative considered, why this choice, tradeoff accepted.\nFormat as ADR markdown with Status, Context, Decision table, Tradeoffs.`,
        template: `# ADR-001: Tech Stack\n\n## Status: Accepted\n\n| Layer | Choice | Alternative | Why |\n|-------|--------|-------------|-----|\n| Mobile + Web | Expo SDK 52 | Flutter | TS, OTA updates |\n| Backend | NestJS | Express | Modular, TS-native |\n| Database | PostgreSQL | MongoDB | ACID, relational |\n| ORM | Prisma | TypeORM | Type-safe, migrations |\n| Container | Docker + K8s (EKS) | ECS | Portable |\n| Cloud | AWS | GCP | Ecosystem |\n\n## Tradeoffs\n- ` },
      { id: "microservices", name: "microservices.md", label: "Microservice Architecture", dp: "jordan",
        what: "Service boundaries, communication patterns, gateway, shared libs.", done: "Each service has clear ownership and API contract.",
        prompt: `You are a CTO designing microservices.\n\nProduct: [PASTE PITCH]\nStories: [PASTE STORIES]\nStack: NestJS + PostgreSQL + K8s on AWS\n\nDesign:\n1. Service decomposition: each with name, responsibility, owned entities, API, dependencies\n2. Communication: sync (HTTP) vs async (SQS/Redis events). Key events each publishes/subscribes\n3. API Gateway: route mapping, auth middleware, rate limiting\n4. Shared libs (@app/common): JWT guard, logger, error filter, health check, correlation ID\n5. Data boundaries: which service owns what, cross-service queries (API, NOT shared DB)\n\nInclude ASCII architecture diagram.`,
        template: `# Microservice Architecture\n\n\`\`\`\n[CloudFront] → [ALB/Ingress]\n                   |\n             [API Gateway]\n              /    |    \\\\\n   [auth-svc]  [core-svc]  [notif-svc]\n      |            |              |\n   [auth_db]   [core_db]       [SQS]\n\`\`\`\n\n## auth-service\n- **Owns**: users, sessions, roles\n- **API**: POST /auth/signup, login, refresh; GET /auth/me\n- **Publishes**: user.created, user.deleted\n\n## Shared Libs (@app/common)\n- JwtAuthGuard, LoggerInterceptor, HttpExceptionFilter, HealthModule` },
      { id: "auth-flow", name: "auth-flow.md", label: "Auth Design", dp: "jordan",
        what: "JWT flow, refresh tokens, storage, password reset, RBAC.", done: "Auth handles all cases: signup, login, refresh, logout, forgot password.",
        prompt: `You are a CTO. Design authentication.\n\nStack: NestJS + Expo + PostgreSQL\nAuth: JWT (access + refresh tokens)\n\nDesign:\n1. Signup: email/password → hash (bcrypt 12) → create user → issue tokens\n2. Login: validate → access token (15min) + refresh token (7d)\n3. Storage: expo-secure-store (mobile), httpOnly cookie (web)\n4. Refresh: validate → rotate (new pair, invalidate old)\n5. Logout: invalidate refresh token server-side\n6. Password reset: email → token (1hr) → reset link\n7. Social login (optional): Google/Apple OAuth\n8. RBAC: USER, ADMIN roles → guards\n9. Security: rate limit login (5/min), blacklist leaked tokens\n\nSequence diagrams (ASCII) for signup, login, refresh.`,
        template: `# Auth Design\n\n## Token Strategy\n- Access: JWT, 15min, in memory (FE)\n- Refresh: opaque, 7d, expo-secure-store / httpOnly cookie\n- On 401 → auto-refresh → retry\n\n## Signup Flow\n\`\`\`\nClient → POST /auth/signup { email, password }\nServer → bcrypt(12) → create user → issue tokens\n\`\`\`\n\n## Roles: USER (default), ADMIN (@Roles decorator + guard)\n\n## Security\n- Rate limit: 5 login/min/IP\n- Refresh rotation: one-use\n- bcrypt 12 rounds, min 8 chars` },
      { id: "data", name: "data-model.md", label: "Data Model (per service)", dp: "jordan",
        what: "Each service's owned entities, typed fields, Prisma schemas.", done: "Can write Prisma schema from this. No cross-service FKs.",
        prompt: `You are a CTO. Design data model PER microservice.\n\nServices: [PASTE MICROSERVICES]\nStories + Criteria: [PASTE]\nORM: Prisma + PostgreSQL\n\nRules:\n- Each service = own PostgreSQL database\n- NO foreign keys across services\n- UUID all IDs\n- createdAt, updatedAt, deletedAt (soft delete) on all\n- Indexes on frequently queried fields\n\nPrisma schema syntax per service.`,
        template: `# Data Model\n\n## auth-service (auth_db)\n\`\`\`prisma\nmodel User {\n  id        String   @id @default(uuid())\n  email     String   @unique\n  password  String\n  role      Role     @default(USER)\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  deletedAt DateTime?\n  sessions  Session[]\n}\n\nmodel Session {\n  id           String   @id @default(uuid())\n  userId       String\n  refreshToken String   @unique\n  expiresAt    DateTime\n  user         User     @relation(fields: [userId], references: [id])\n}\n\nenum Role { USER ADMIN }\n\`\`\`` },
      { id: "api", name: "api-contract.md", label: "API Contracts", dp: "jordan",
        what: "Every endpoint: method, path, input, output, errors, auth level.", done: "Frontend and each service buildable independently.",
        prompt: `You are a CTO. Define API contracts PER microservice.\n\nServices + Data: [PASTE]\nAuth: [PASTE AUTH FLOW]\nStories: [PASTE]\n\nPer endpoint: method, path, auth (public/user/admin), request body (TS interface), response body (TS), errors (status + body), rate limit.\n\nShared types: ApiError, Paginated<T>, auth header format.\nTypeScript interfaces.`,
        template: `# API Contracts\n\n## Shared Types\n\`\`\`ts\ninterface ApiError { statusCode: number; message: string; error: string; }\ninterface Paginated<T> { data: T[]; meta: { total: number; page: number; limit: number; }; }\n\`\`\`\n\n## auth-service\n### POST /api/auth/signup [public]\n- Body: { email, password }\n- 201: { user, accessToken, refreshToken }\n- 400: validation | 409: exists` },
      { id: "infra", name: "infra-design.md", label: "Infrastructure Design", dp: "alex",
        what: "AWS services, K8s cluster, networking, secrets, environments.", done: "Can draw the entire infra on a whiteboard.",
        prompt: `DevOps architect. Design AWS + K8s infrastructure.\n\nStack: NestJS microservices + PostgreSQL + Expo (web)\nCloud: AWS, Container: K8s (EKS)\n\nDesign:\n1. AWS: EKS, RDS, ECR, S3, CloudFront, SQS, Route53, ACM, Secrets Manager, CloudWatch\n2. K8s: namespaces, per-service resources (Deployment, Service, HPA, ConfigMap, Secret)\n3. Network: VPC, public + private subnets, ALB, security groups\n4. Environments: dev (small) → staging (mirror) → prod (multi-AZ, auto-scale)\n5. Cost estimate\n\nASCII diagram.`,
        template: `# Infrastructure Design\n\n\`\`\`\n[Route53] → [CloudFront] → [S3: web]\n                |\n           [ALB/Ingress]\n                |\n          [EKS Cluster]\n   ┌────────┼────────┐\n[gateway] [auth] [core] ← private subnet\n             |      |\n          [RDS]  [RDS]   [SQS]\n\`\`\`\n\n| Service | Dev | Prod |\n|---------|-----|------|\n| EKS | t3.medium x2 | t3.large x3 + HPA |\n| RDS | db.t3.micro | db.r5.large multi-AZ |` },
    ],
    gate: "Trace each story: UI → gateway → service → DB → response. Every boundary clear.",
  },
  {
    id: "03-design-ui", num: 3, name: "Design UI", icon: "🎨", color: "#EC4899",
    duration: "2-3 days", goal: "Every screen with all states before coding",
    files: [
      { id: "screens", name: "screen-inventory.md", label: "Screen Inventory", dp: "yuki",
        what: "Every screen: name, purpose, elements, platform diffs.", done: "A screen per user story.",
        prompt: `UX designer. List every screen for Expo (web + iOS + Android).\n\nProduct: [PASTE PITCH]\nStories: [PASTE]\n\nPer screen: name, purpose (story), key elements, primary action.\nGroup: Auth, Main tabs, Detail/Form, Modals.\nNote platform differences.`,
        template: `# Screen Inventory\n\n## Auth\n| Screen | Purpose | Elements | Action |\n|--------|---------|----------|--------|\n| Login | S1 | email, password, submit, social | Sign in |\n| Register | S1 | fields, submit | Create account |\n| Forgot | S1 | email, submit | Send reset |` },
      { id: "flows", name: "user-flows.md", label: "User Flows", dp: "yuki",
        what: "Entry → action → result → next screen per story.", done: "Every story traceable as screen sequence.",
        prompt: `UX designer. Map user flows.\n\nScreens: [PASTE]\nStories: [PASTE]\n\nPer flow: screen sequence, happy path, error path, platform differences.`,
        template: `# User Flows\n\n## Flow 1: [action]\n\`\`\`\nLogin → Home → List → Tap → Detail → Edit → Save → Back\n\`\`\`\n### Happy path\n### Error path\n### Platform diff` },
      { id: "states", name: "screen-states.md", label: "Screen States", dp: "yuki",
        what: "Every screen: loading, empty, populated, error + edge cases.", done: "No happy-path-only designs.",
        prompt: `UX designer. ALL states per screen.\n\nScreens: [PASTE]\n\nPer screen: loading (skeleton), empty (message + CTA), populated, error (recovery).\nEdge cases: keyboard, long text, offline, safe area, accessibility.`,
        template: `# Screen States\n\n## [Screen]\n### Loading → Skeleton\n### Empty → Message + CTA\n### Error → Message + Retry\n### Edge Cases\n- [ ] KeyboardAvoidingView\n- [ ] SafeAreaView\n- [ ] Offline\n- [ ] Accessibility labels` },
      { id: "nav", name: "navigation-map.md", label: "Navigation Map", dp: "yuki",
        what: "Expo Router file structure + deep links + auth guard.", done: "Nav matches screens 1:1.",
        prompt: `UX + dev. Expo Router navigation map.\n\nScreens: [PASTE]\nAuth: [PASTE]\n\nProvide: app/ structure, layout groups, deep links, auth guard, tab bar config, platform nav differences.`,
        template: `# Navigation Map\n\n\`\`\`\napp/\n  _layout.tsx\n  (auth)/ login.tsx, register.tsx, forgot.tsx\n  (tabs)/ index.tsx, [entity]/, settings.tsx\n\`\`\`` },
      { id: "responsive", name: "responsive-strategy.md", label: "Responsive Strategy", dp: "yuki",
        what: "How the app adapts across mobile, tablet, web.", done: "Layout works at every breakpoint.",
        prompt: `UX engineer. Responsive strategy for Expo + NativeWind.\n\nBreakpoints, layout patterns, nav (tabs→sidebar), touch targets, typography, Platform utilities.`,
        template: `# Responsive Strategy\n\n## Breakpoints\n- Mobile: default\n- Tablet: md: (768px)\n- Desktop: lg: (1024px)\n\n## Touch: min h-11 w-11\n## Web: hover: states` },
    ],
    gate: "Every screen has all states. Responsive mobile → web.",
  },
  {
    id: "04-plan", num: 4, name: "Plan & Roadmap", icon: "📊", color: "#F97316",
    duration: "1-2 days", goal: "Roadmap + tasks + repos initialized + CI green",
    files: [
      { id: "roadmap", name: "roadmap.md", label: "Product Roadmap", dp: "sara",
        what: "3-6 month plan: MVP → Beta → Launch → Growth → Scale.", done: "Clear path from v0.1 to v1.0+.",
        prompt: `Product manager. Create roadmap.\n\nProduct: [PASTE PITCH]\nStories: [PASTE ALL]\nStack: Expo + NestJS + K8s/AWS\n\nPhases: MVP (2-4w), Beta (4-8w), Launch (8-12w), Growth (3-6mo), Scale (6-12mo).\nPer phase: goal, features, infra milestone, metric, risk.`,
        template: `# Product Roadmap\n\n## Phase 1: MVP (Weeks 1-4)\n**Goal**: Core e2e\n**Features**: \n**Infra**: Dev K8s, 2 services\n**Metric**: \n\n## Phase 2: Beta (Weeks 5-8)\n## Phase 3: Launch (Weeks 9-12)\n## Phase 4: Growth (Months 3-6)\n## Phase 5: Scale (Months 6-12)` },
      { id: "m-current", name: "milestone-current.md", label: "Current Milestone", dp: "sara",
        what: "Smallest shippable set a user can test.", done: "1-2 week scope. Core flow works.",
        prompt: `Define current milestone. Goal, tasks, excluded, done when, estimate.`,
        template: `# Milestone 1: [Name]\n\n## Goal: [user can...]\n## Tasks: \n- [ ] \n## NOT included (M2):\n## Done when: [e2e flow]\n## Duration: [X] days` },
      { id: "tasks", name: "task-list.md", label: "Task List (Ordered)", dp: "marcus",
        what: "Stories → dev tasks, dependency-ordered, estimated, tagged.", done: "Clear first → last.",
        prompt: `Tech lead. Break stories into tasks.\n\nStories + Criteria: [PASTE]\nMilestone: [PASTE]\n\nTag: [FE], [BE], [INFRA]. Order: infra → DB → auth → core → gateway → frontend → integration.\nEstimate 0.5-2d each.`,
        template: `# Tasks — Milestone [N]\n\n| # | Tag | Task | Story | Est | Depends |\n|---|-----|------|-------|-----|---------|` },
      { id: "setup-fe", name: "setup-frontend.md", label: "Frontend Setup (Expo)", dp: "alex",
        what: "Expo init, deps, folder structure, env, test config.", done: "expo start works, jest green.",
        prompt: `DevOps. Expo setup. SDK 52, Router, Zustand, NativeWind, RNTL, MSW, Jest.\nExact commands. Folder structure. Config files.`,
        template: `# Frontend Setup\n\n\`\`\`bash\nnpx create-expo-app@latest my-app --template tabs\ncd my-app\nnpx expo install zustand nativewind expo-secure-store\nnpm i -D tailwindcss @testing-library/react-native msw jest-expo\n\`\`\`\n\n## Verify\n- [ ] expo start → loads\n- [ ] npm test → green` },
      { id: "setup-be", name: "setup-backend.md", label: "Backend Setup (NestJS)", dp: "alex",
        what: "NestJS monorepo, services, Prisma, Docker, docker-compose.", done: "docker compose up → healthy.",
        prompt: `DevOps. NestJS monorepo setup. Nest CLI, apps (auth, core, gateway), shared lib, Prisma per service, Dockerfiles, docker-compose, health checks, test setup.`,
        template: `# Backend Setup\n\n\`\`\`bash\nnest new backend && cd backend\nnest g app auth-service\nnest g app core-service\nnest g app api-gateway\nnest g lib common\n\`\`\`\n\n## Verify\n- [ ] docker compose up → healthy\n- [ ] prisma migrate → done\n- [ ] npm test → green` },
      { id: "cicd", name: "ci-cd.md", label: "CI/CD Pipeline", dp: "alex",
        what: "GitHub Actions: test → build → ECR → K8s. Plus Expo builds.", done: "Push to main → deployed.",
        prompt: `DevOps. CI/CD for NestJS + Expo + AWS (ECR, EKS) + GitHub Actions.\n\nBackend CI (PR): lint, test, integration. Backend CD (merge): Docker → ECR → K8s.\nFrontend CI: lint, test. Frontend CD: EAS Build/Submit + expo export → S3.\nYAML examples.`,
        template: `# CI/CD\n\n## Backend CI (.github/workflows/backend-ci.yml)\n\`\`\`yaml\nname: Backend CI\non: { pull_request: { paths: [\"backend/**\"] } }\n\`\`\`\n\n## Frontend: EAS Build + S3` },
      { id: "env", name: "env-management.md", label: "Environment Management", dp: "alex",
        what: "Env vars: .env → K8s ConfigMap/Secret → AWS Secrets Manager.", done: "No secrets in code.",
        prompt: `DevOps. Environment management for NestJS + Expo + K8s + AWS.\n\nLocal .env, EXPO_PUBLIC_ prefix, NestJS ConfigModule + Joi, K8s ConfigMap/Secret + external-secrets, GitHub secrets, rotation strategy.\nList every env var per service.`,
        template: `# Environment Management\n\n## Frontend\n\`\`\`\nEXPO_PUBLIC_API_URL=http://localhost:3000\n\`\`\`\n\n## auth-service\n| Var | Secret? | Source |\n|-----|---------|--------|\n| DATABASE_URL | ✅ | AWS SM → K8s Secret |\n| JWT_SECRET | ✅ | AWS SM → K8s Secret |` },
    ],
    gate: "Repos init. Docker works. CI green. Roadmap approved. Env documented.",
  },
  {
    id: "05-build", num: 5, name: "Build (TDD)", icon: "🔨", color: "#F59E0B",
    duration: "Per issue: hours to 2 days", goal: "RED → GREEN → REFACTOR per criterion",
    files: [
      { id: "test-strategy", name: "test-strategy.md", label: "Test Strategy", dp: "marcus",
        what: "Test types, tools, coverage, what NOT to test. Expo + NestJS.", done: "Plan covers both layers.",
        prompt: `Senior dev. Test strategy.\n\nFE: Expo + RNTL + Jest + MSW. BE: NestJS + Jest + Supertest + Prisma test DB.\n\nPer layer: types + tools, what to test, NOT test, coverage, mocks, conventions.\nContract testing (shared DTOs), test data factories.`,
        template: `# Test Strategy\n\n## Frontend: Unit (Jest), Component (RNTL), Integration (MSW)\n## Backend: Unit (Jest), Integration (Supertest), E2E (test DB)\n## Coverage: FE 70%, BE 80%\n## NOT: framework internals, third-party UIs` },
      { id: "tdd-red", name: "tdd-01-red.md", label: "🔴 RED Phase", dp: "marcus",
        what: "Failing tests FIRST per criterion. Both FE and BE.", done: "Every criterion has failing tests.",
        prompt: `TDD RED. ONLY failing tests.\n\nIssue: [TITLE]\nCriteria: [PASTE]\n\nBE: NestJS service test + Supertest. FE: RNTL + MSW.\nOne test per criterion per layer. Tests MUST fail.`,
        template: `# 🔴 RED — [Issue] [title]\n\n## Criterion 1\n### Backend Test\n\`\`\`ts\ndescribe('[Service]', () => {\n  it('should [behavior]', async () => { });\n});\n\`\`\`\n### Frontend Test\n\`\`\`ts\ndescribe('[Feature]', () => {\n  it('should [behavior]', () => { });\n});\n\`\`\`\n### ❌ FAIL` },
      { id: "tdd-green", name: "tdd-02-green.md", label: "🟢 GREEN Phase", dp: "marcus",
        what: "Minimum code to pass each test.", done: "All RED tests pass.",
        prompt: `TDD GREEN. Minimum code.\n\nFailing tests: [PASTE RED]\nErrors: [PASTE]\n\nSimplest code. BE: service + controller + Prisma. FE: component + API call.`,
        template: `# 🟢 GREEN — [Issue]\n\n## Criterion 1\n### Backend\n\`\`\`ts\n// service + controller\n\`\`\`\n### Frontend\n\`\`\`ts\n// component/hook\n\`\`\`\n### ✅ PASS` },
      { id: "tdd-refactor", name: "tdd-03-refactor.md", label: "🔵 REFACTOR Phase", dp: "marcus",
        what: "Types, helpers, error handling, edge cases.", done: "Clean. Tests green. Edges covered.",
        prompt: `TDD REFACTOR.\n\nCode: [PASTE GREEN]\nTests: [PASTE]\n\nTypes, NestJS pipes/guards, error handling, extract helpers, edge cases.\nNew edge = failing test first, then fix.`,
        template: `# 🔵 REFACTOR — [Issue]\n\n## Types\n## Error Handling\n## New Edge Cases + Tests\n## Final: all ✅, coverage [X]%` },
      { id: "tdd-comp", name: "tdd-04-components.md", label: "Component Tests", dp: "marcus",
        what: "Expo components: render, interactions, all states.", done: "Every component tested.",
        prompt: `Component tests (RNTL + MSW).\n\nComponent: [NAME]\nStates: [PASTE]\n\nTest: render, loading, empty, error, interactions, validation, accessibility.`,
        template: `# Component Tests — [Component]\n\n\`\`\`ts\n// RNTL + MSW\ndescribe('[Component]', () => {\n  it('populated state', () => { });\n  it('loading', () => { });\n  it('empty + CTA', () => { });\n  it('error + retry', () => { });\n  it('[interaction]', async () => { });\n});\n\`\`\`` },
      { id: "tdd-api", name: "tdd-05-api-tests.md", label: "API Integration Tests", dp: "marcus",
        what: "NestJS e2e: request → DB → response.", done: "Every endpoint tested with real DB.",
        prompt: `NestJS integration tests.\n\nService: [NAME]\nEndpoints: [PASTE]\n\nPer endpoint: seed DB, supertest request, assert response + DB state.\nHappy, validation (400), not found (404), unauthorized (401).`,
        template: `# API Tests — [service]\n\n\`\`\`ts\n// NestJS Test + supertest\ndescribe('[Service] e2e', () => {\n  describe('POST /api/[resource]', () => {\n    it('creates (201)', async () => { });\n    it('validates (400)', async () => { });\n    it('rejects unauth (401)', async () => { });\n  });\n});\n\`\`\`` },
    ],
    gate: "All green. Coverage > 70% FE, > 80% BE. Every criterion RED→GREEN→REFACTOR.",
  },
  {
    id: "06-review", num: 6, name: "Review", icon: "🔍", color: "#10B981",
    duration: "30-60 min per PR", goal: "Self-review + security + infra check",
    files: [
      { id: "pr", name: "pr-checklist.md", label: "PR Review Checklist", dp: "marcus",
        what: "Self-review every line. Check both FE and BE.", done: "All items pass. CI green.",
        prompt: `Code review for Expo + NestJS + K8s.\n\nDiff: [PASTE]\n\nCheck: tests, no debug code, no secrets, error handling, Prisma (N+1), NestJS (guards), Expo (platforms), K8s (limits).`,
        template: `# PR Review: [title]\n\n- [ ] Every criterion tested\n- [ ] No debug code\n- [ ] No hardcoded secrets\n- [ ] Error handling\n- [ ] Prisma: no N+1\n- [ ] Guards on protected routes\n- [ ] Works all platforms` },
      { id: "security", name: "security-review.md", label: "Security Review", dp: "alex",
        what: "Auth, secrets, K8s, network, dependencies.", done: "No critical issues.",
        prompt: `Security review for Expo + NestJS + K8s + AWS.\n\nCheck: auth (JWT, storage, refresh), API (rate limit, validation, CORS, helmet), secrets (AWS SM, K8s), DB (parameterized, pooling, encryption), K8s (RBAC, network policies, non-root), deps (npm audit), mobile (secure-store).`,
        template: `# Security Review\n\n## Auth\n- [ ] JWT secret in AWS SM\n- [ ] expo-secure-store\n- [ ] Refresh rotation\n- [ ] bcrypt ≥12\n\n## K8s\n- [ ] Non-root\n- [ ] Network policies\n- [ ] Resource limits\n\n## Deps\n- [ ] npm audit: 0 critical` },
    ],
    gate: "Coverage met. Security passed. CI green.",
  },
  {
    id: "07-qa", num: 7, name: "QA", icon: "🧪", color: "#EF4444",
    duration: "2-4 hrs per milestone", goal: "Break frontend, backend, infra",
    files: [
      { id: "qa-fe", name: "qa-frontend.md", label: "Frontend QA", dp: "taylor",
        what: "Every flow on iOS, Android, Web. Break inputs, states, offline.", done: "Critical paths pass all platforms.",
        prompt: `QA Expo (iOS + Android + Web).\n\nFeatures: [LIST]\n\nTest: critical paths per platform, edge cases, accessibility (VoiceOver, TalkBack, keyboard), responsive.`,
        template: `# Frontend QA\n\n## Critical Paths\n| Test | iOS | Android | Web |\n|------|-----|---------|-----|\n\n## Edge Cases\n| Test | Result |\n|------|--------|\n\n## Accessibility\n- [ ] VoiceOver\n- [ ] TalkBack\n- [ ] Keyboard nav\n\n## Bugs\n| # | Sev | Platform | Desc | Status |\n|---|-----|----------|------|--------|` },
      { id: "qa-be", name: "qa-backend.md", label: "Backend + Load QA", dp: "taylor",
        what: "API tests, load tests, K8s health.", done: "APIs handle load. No 5xx.",
        prompt: `QA NestJS + K8s.\n\nEndpoints: [PASTE]\n\nAPI: every endpoint happy + error. Load (k6): target users, p95 < 500ms, errors < 1%. K8s: pods, HPA, logs.`,
        template: `# Backend QA\n\n## API\n| Service | Endpoint | Happy | Error |\n|---------|----------|-------|-------|\n\n## Load Test\n| Metric | Target | Actual |\n|--------|--------|--------|\n| p95 | < 500ms | |\n| Errors | < 1% | |\n\n## K8s\n- [ ] Pods running\n- [ ] HPA configured` },
    ],
    gate: "P1 bugs fixed. Paths pass. Load OK.",
  },
  {
    id: "08-ship", num: 8, name: "Ship", icon: "🚀", color: "#F43F5E",
    duration: "4-8 hours", goal: "Deploy: K8s + stores + web",
    files: [
      { id: "infra-ready", name: "infra-checklist.md", label: "Infrastructure Readiness", dp: "alex",
        what: "AWS + K8s production readiness.", done: "Prod infra tested + monitored.",
        prompt: `Production readiness for AWS + K8s.\n\nEKS (multi-AZ, HPA, PDB), RDS (backups, encryption), networking, DNS/SSL, monitoring (Prometheus + Grafana + Sentry + CloudWatch), logging, secrets, scaling, rollback.`,
        template: `# Infra Readiness\n\n## EKS: [ ] multi-AZ, [ ] HPA, [ ] limits\n## RDS: [ ] multi-AZ, [ ] backups, [ ] encryption\n## Monitoring: [ ] Prometheus, [ ] Sentry, [ ] alerts\n## Rollback: kubectl rollout undo + RDS snapshot` },
      { id: "deploy", name: "deploy-steps.md", label: "Deploy Steps", dp: "alex",
        what: "Exact commands: backend → K8s, mobile → stores, web → CDN.", done: "All deployed. Smoke tested.",
        prompt: `Step-by-step deployment.\n\n1. Backend: Docker → ECR → K8s → Prisma migrate\n2. Mobile: eas build --production → eas submit\n3. Web: expo export → S3 → CloudFront\n4. OTA: eas update\n5. Smoke tests`,
        template: `# Deploy v[X.Y.Z]\n\n## Backend → K8s\n\`\`\`bash\n# build, push ECR, kubectl set image, prisma migrate\n\`\`\`\n## Mobile → Stores\n\`\`\`bash\neas build --platform all --profile production\neas submit\n\`\`\`\n## Web → CDN\n\`\`\`bash\nnpx expo export --platform web\naws s3 sync dist/ s3://[bucket]\n\`\`\`\n## Smoke: [ ] iOS [ ] Android [ ] Web [ ] API` },
      { id: "release", name: "release-notes.md", label: "Release Notes", dp: "sara",
        what: "What shipped, services updated, known issues.", done: "Tagged. Noted. Notified.",
        prompt: `Release notes. Version, features, services, platforms, known issues.`,
        template: `# v[X.Y.Z] — [Name]\n\n## New\n- \n## Services: auth, core\n## Platforms: iOS, Android, Web, K8s\n## Known Issues\n- ` },
    ],
    gate: "Smoke tested on real devices + prod API. Monitoring clean.",
  },
  {
    id: "09-sell", num: 9, name: "Sell", icon: "💰", color: "#8B5CF6",
    duration: "Ongoing", goal: "Get users + revenue",
    files: [
      { id: "launch", name: "launch-strategy.md", label: "Launch Strategy", dp: "sara",
        what: "Pre-launch, launch day, post-launch. First 100 users.", done: "Clear plan with timeline.",
        prompt: `Launch strategy.\n\nProduct: [PASTE PITCH]\nTarget: [PASTE PERSONAS]\nPlatforms: iOS, Android, Web\n\nPre-launch (2w), launch channels, launch day sequence, post-launch, metrics.`,
        template: `# Launch Strategy\n\n## Target: 100 users in [X] days\n\n## Pre-Launch\n- [ ] Landing page\n- [ ] Beta testers\n\n## Channels\n| Channel | Tactic | Expected |\n|---------|--------|----------|` },
      { id: "aso", name: "app-store-listing.md", label: "App Store Optimization", dp: "sara",
        what: "iOS + Android store listings: title, keywords, screenshots.", done: "Both listings ready.",
        prompt: `ASO expert. Store listings for iOS + Android.\n\nPer platform: name, subtitle/short desc, keywords, full description, What's New, screenshot strategy, category.`,
        template: `# App Store Listings\n\n## iOS\n- **Name**: [30 chars]\n- **Subtitle**: [30 chars]\n- **Keywords**: [100 chars]\n\n## Google Play\n- **Name**: [50 chars]\n- **Short**: [80 chars]\n\n## Screenshots\n1. Hero\n2. Feature 1\n3. Feature 2\n4. Social proof\n5. CTA` },
      { id: "landing", name: "landing-page.md", label: "Landing Page", dp: "yuki",
        what: "Hero, problem, solution, pricing, CTA.", done: "Copy + design spec ready.",
        prompt: `Landing page copy + design.\n\nProduct: [PASTE PITCH]\n\nHero (headline, subhead, CTA, store badges), Problem, Solution (3 benefits), How It Works (3 steps), Pricing, Final CTA.\nDesign notes: colors, fonts, layout.`,
        template: `# Landing Page\n\n## Hero\n**Headline**: \n**Subhead**: \n**CTA**: [Get Started Free]\n\n## Problem → Solution → How It Works → Pricing → CTA` },
      { id: "pricing", name: "pricing.md", label: "Pricing Model", dp: "sara",
        what: "Free vs paid, upgrade trigger, revenue projection.", done: "Model ready.",
        prompt: `Design pricing. Model type, tiers, upgrade trigger, price justification, revenue projection.`,
        template: `# Pricing\n\n| | Free | Pro |\n|-|------|-----|\n| Price | $0 | $[X]/mo |\n\n## Revenue: [N] × [X]% × $[Y] = $[Z] MRR` },
      { id: "growth", name: "growth-plan.md", label: "Growth Plan", dp: "sara",
        what: "Channels, content, retention, referral, weekly actions.", done: "3-month plan.",
        prompt: `3-month growth. Channels ranked, content strategy, retention loops, referral, monthly milestones, weekly checklist.`,
        template: `# Growth — 3 Months\n\n| Month | Users | MRR |\n|-------|-------|-----|\n\n## Channels\n## Retention\n## Weekly\n- [ ] ` },
    ],
    gate: "Landing + stores live. First 10 users. Feedback loop.",
  },
  {
    id: "10-iterate", num: 10, name: "Iterate", icon: "🔄", color: "#6366F1",
    duration: "Half day → Build", goal: "Learn → plan → repeat",
    files: [
      { id: "retro", name: "retro.md", label: "Sprint Retro", dp: "sara",
        what: "What worked, slow, infra issues, estimation accuracy.", done: "Better estimates.",
        prompt: `Sprint retro. Planned vs actual, surprises, infra issues, 3 takeaways, adjustment factor.`,
        template: `# Retro — Milestone [N]\n\n## Went well\n## Slow\n| Task | Est | Actual | Why |\n|------|-----|--------|-----|\n## Takeaways\n1. \n## Adjust: ×[factor]` },
      { id: "next", name: "milestone-next.md", label: "Next Milestone", dp: "sara",
        what: "Based on retro + usage + roadmap.", done: "Defined. Back to Build.",
        prompt: `Next milestone. Retro, roadmap, feedback, bugs.\nPrioritize: bugs > stability > pain > features.`,
        template: `# Milestone [N+1]\n\n| # | Tag | Task | Est |\n|---|-----|------|----- |\n\n→ Back to Phase 5` },
    ],
    gate: "Back to Phase 5. This loop IS software development.",
  },
];
